baseURL: https://rotex1800.de
languageCode: de-de
title: Rotex 1800 e.V.
theme: hugo-whisper-theme
build:
  writeStats: true

params:
  showPostsOnHomepage: true
  showDateOnPosts: true
  addFrame: true

taxonomies:
  category: categories

enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true