name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    environment: Beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Hugo Build
        uses: lowply/build-hugo@v0.88.1

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./public/

      - name: Upload with FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          local-dir: public/
          state-name: ../.ftp-deploy-sync-state.json
          submodules: recursive
          server: w00a5ba0.kasserver.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
